apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: bounced-service.default.svc.cluster.local
  namespace: default
spec:
  routes:
  - condition:
      method: GET
      pathRegex: /.*
    name: GET /
    isRetryable: true
  retryBudget:
    retryRatio: 0.2
    minRetriesPerSecond: 10
    ttl: 10s